---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
spec:
  chartRef:
    kind: OCIRepository
    name: csi-driver-smb
  interval: 1h
  values:
    windows:
      enabled: false
    storageClasses:
      - name: smb-csi
        parameters:
          source: "//smb-server.default.svc.cluster.local/media"
          csi.storage.k8s.io/node-stage-secret-name: smbcreds
          csi.storage.k8s.io/node-stage-secret-namespace: kube-system
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        mountOptions:
          - dir_mode=0777
          - file_mode=0777
          - noperm
          - mfsymlinks
          - cache=strict
          - noserverino
