---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./aqua.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./crunchydata.yaml
  - ./csi-driver-nfs.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./dysnix.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./falco-security.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./istio.yaml
  - ./jetstack.yaml
  - ./kepler.yaml
  - ./kubernetes-dashboard.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./neuvector.yaml
  - ./nvidia.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./stevehipwell.yaml
  - ./weaveworks.yaml
  - ./xentra.yaml
