---
- name: Create node-exporter directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ podman_base_dir }}/node-exporter"


# Disable running container if it is already running in systemd
- name: Disable node-exporter container
  ansible.builtin.systemd:
    name: container-node-exporter.service
    state: stopped
    enabled: false

- name: Create node-exporter container
  containers.podman.podman_container:
    name: node-exporter
    recreate: true
    privileged: true
    state: started
    restart_policy: unless-stopped
    image: quay.io/prometheus/node-exporter:v1.6.1
    ports:
      - 9100:9100
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro,rslave
    generate_systemd:
      path: /etc/systemd/system
      restart_policy: always
      names: true
      new: true

- name: Enable node-exporter container
  ansible.builtin.systemd:
    name: container-node-exporter.service
    state: started
    enabled: true
