---
# yaml-language-server: $schema=https://kubernetes-schemas.witl.xyz/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: flux-system
spec:
  interval: 2h
  url: oci://ghcr.io/bjw-s/app-template
