apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    hajimari.io/enable: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100000m
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-body-buffer-size: 10000M
  #  hajimari.io/icon:
  name: perforce
  namespace: external
spec:
  rules:
  - host: perforce.${SECRET_DOMAIN_STUDIO}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: perforce
            port:
              number: 1666
  tls:
  - hosts:
    - perforce.${SECRET_DOMAIN_STUDIO}
    secretName: perforce-cert
