---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blackbox-exporter
  - grafana
  - kube-prometheus-stack
  - loki
  - node-problem-detector
  - snmp-exporter
  - speedtest-exporter
  - thanos
  - vector
