---
# yaml-language-server: $schema=https://kubernetes-schemas.witl.xyz/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-excalidraw
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/tools/excalidraw/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: excalidraw
      namespace: tools
  interval: 30m
  retryInterval: 1m
  timeout: 3m
