---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret-alertmanager-global.yaml
  - ./externalsecret-mimir-oauth.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./rbac-mimir-rules.yaml
