apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: external
  annotations: {}
  #  traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  type: ExternalName
  externalName: "${NAS_ADDR}"
  ports:
    - port: 9080
