---
#
# SECRET* vars are encrypted with sops
#

# -- Base Docker Directory
docker_base_dir: /opt/docker

# -- Base ZFS Dataset
zfs_zpool_base_dir: /cairo

# -- Vector Aggregator Address
vector_aggregator_addr: "10.0.42.6"

# -- Vector Aggregator Port
vector_aggregator_port: "6000"
