---
# yaml-language-server: $schema=https://kubernetes-schemas.witl.xyz/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-snmp-exporter-dell-idrac
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/monitoring/snmp-exporter/dell-idrac
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: snmp-exporter-dell-idrac
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 30s
