# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:2rZnzVbTJQ==,iv:ZTpGAWRe36QraeCxzL89e3cDb3bE39m6Xz6UO0H9AoA=,tag:Mhu32i+/xxfJK4KeOPHzxw==,type:str]
    SECRET_DOMAIN_GAMES: ENC[AES256_GCM,data:0aQBJgwMrZxt0bhq,iv:KzzXSdsYBDx1n71mFb6R0kmD5t27S71tzJOO49UQHqU=,tag:tz2P7g7CGaZDwYxzWEtalg==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:HR5lYxDFQe0=,iv:4WMysB8X9cTt/dkq/MhOerGthDLRsXWXFG51LNUHCGM=,tag:GHK0h9E7RpstchDGtth9+w==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:4qTCcQqUGw==,iv:OO7/4hoa7CzkVFrV4ti9uLOyKYYR1WZTMwUNlTK1vAA=,tag:xyr/NDeuDRbsM2w3iXcESw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:6NfNBsTnY49Rw6v23lMP/8ls5dhL,iv:fh5ueCnaGW98dctCtT+bOHB5g3pI9z90thZG85vpiZc=,tag:Hu/vz5uJTEAjbDS+PnU30w==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:pekzHHNEClF6H5ce607F/ccvRI66NcEgFWW+DYfX,iv:hiBS6DZ0cezvyJwBYzJJtZXJOW6njKfsfSim/MvIMno=,tag:dPXQ3m/W12NMkmkw7DiORA==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:spemlxrsL7jHGyxMX7XU4IBV2MeHnGFW7ws/odtO,iv:3C4GffMBILVBfdXc4NnULn+jaek668J3OK0e0Z/pHTI=,tag:1czj6QH/gg9WurrzTy4NkA==,type:str]
    SECRET_ALERTMANAGER_UPTIMEROBOT_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:cdfeWLL9WwaFx0K+qiY9qcussYFZsCKophLm6kOXoeEd8tyTDJXMCmLXnCrD+l93g+vG,iv:elC9tm7OEWZKSAjfeg4GJijgETfNmp+09T0jiLwUUuc=,tag:EysVpCHhjMd0JNHjqMxtHQ==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:vG5SXwOVMOXbL8KWTbQebYEIFNGMy2I9pD6t1rNhsq0=,iv:IebXZYEOaiVVbEOqvkukxE7TT220HgYBHy4PonwCKqA=,tag:UBGqnsJCmp9WxPR1Bof5Lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNllpb29Camx2dGVHYXg3
            UGVoMnFBTHBEdTZzZGxEUEozY0htUFRaT2dBCkZWM2RXMFNZTHkzSzVESmp3Qkl3
            YkJPcWNISk8vRUVKbStsU05GWnU4YVUKLS0tIDAvdEo3bDhEVzlQWTk2Sng0SWRD
            L1NsU2F1RXNtUDRtcmRkM3pTODlIVzQKChJ1CcCEk6XsGLQRt+1xKBZU+3tE022e
            5Zgmrw3z4O6EnRT/oryzlgHjY7JDmklD6q4cu0oeU08p4oApqYmkbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T00:05:38Z"
    mac: ENC[AES256_GCM,data:Q5yqDFmqVW/mgjMS9qh7al7uBoN+k1dt1FcN2RGdWwuMnENey3Az1otNewFg3U166EzabBFN7rF+7rwMUS/0/cMdExv8ChbNz2kwzqt8E/gb8aZa27p5cPiN16ZpkQc8JIf00C7/16tWi5JLWJnxzA6t5Ev6O/iLspVcSCJFQFY=,iv:NFF0VLgg7eElSybQz15l7uimFGuNEZJFC7LqfQj7BMQ=,tag:go79kpL2df0Ou9BO7Qgt8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
