---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: kyak
  TIMEZONE: "America/New_York"
  NET_NODE_CIDR: "10.10.10.0/24"
  NET_POD_CIDR: "10.69.0.0/16"
  NET_SVC_CIDR: "10.96.0.0/16"
  NET_EIP_CIDR: "10.0.42.0/24"
  SVC_NGINX_ADDR: "10.0.42.2"
  SVC_LLDAP_ADDR: "10.0.42.3"
  SVC_INTERNAL_NGINX_ADDR: "10.0.42.4"
  SVC_QBITTORRENT_ADDR: "10.0.42.5"
  SVC_VECTOR_ADDR: "10.0.42.6"
  SVC_JELLYFIN_ADDR: "10.0.42.8"
  SVC_REDIS_ADDR: "10.0.42.11"
  SVC_POSTGRES_ADDR: "10.0.42.12"
  CLUSTER_CLOUDFLARE_TUNNEL_ID: eebc7cde-6d81-440b-9e15-84e574762367
