---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-system
  - ./auth
  - ./cert-manager
  - ./database
  - ./flux-system
  - ./falco-system
  - ./kube-system
  - ./kyverno
  - ./media
  - ./monitoring
  - ./networking
  - ./rook-ceph
  - ./storage
  - ./tools
  - ./volsync
