---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media-browser
  - overseerr
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - radarr-uhd
  - sonarr
  - sonarr-uhd
  - tautulli
  - trash-updater
  - unpackerr
