---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home.yaml
  - k10-disaster-recovery.yaml
  - media.yaml
  - secret.sops.yaml
  - pod-spec-override.yaml
  - tools.yaml
